= 5to6-perlop
:toc-title: 目录
:description: Perl 5 to Perl 6 指南 - 运算符
:keywords: perl6, perl 6, perl 6 document
:Email: blackcatoverwall@gmail.com
:Revision: 1.0
:icons: font
:source-highlighter: pygments
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:doctype: book
:lang: zh

== 描述

一个全面的（希望如此）Perl 5运算符在 Perl 6中的等价物列表，并在必要时记录他们的差异。

== 注意
:star: *

这份文档将不会详细的介绍运算符，它意在指导你了解 Perl 5文档中的运算符在 Perl 6中的等价物。
对于等价物的全部文档，请参考 https://docs.perl6.org/language/operators[Perl 6 documentation]。

=== 运算符优先级以及结合性

Perl 6中运算符的优先级不同于 Perl 5，所以它将__不会__详细的列在这里。
如果你想了解 Perl 6中运算符的优先级以及结合性，请参考 https://docs.perl6.org/language/operators#Operator_Precedence[Operator Precedence]

=== 项以及列表运算符

在Perl 5运算符文档中列出的一元或者列表运算符在本节也被认为是函数，比如 `print` 以及 `chdir`。
像这样的，你可以在 https://docs.perl6.org/language/5to6-perlfunc[5to6-perlfunc]中找到相关的信息，
圆括号依然用于分组。

=== 箭头运算符

由于 Perl 6中不会经常使用引用，所以箭头作为解引用运算符不太有用。
如果你需要对某物解引用，那么箭头要替换成点。
对于方法调用也是点。
所以在 Perl 6中，Perl 5中的 `$arrayref->[7]` 变成了 `$array.[7]`，类似的，`$user->name`
变成了 `$user.name`。
胖箭头 `\=>` 现在用于构造 Pairs，见 https://docs.perl6.org/language/terms#Pair[Pair term documentation]。

=== 自增和自减

和 Perl 5中一样可用，一个可能的告诫就是它们可以通过调用方法 `succ` 以及 `pred` 来达到 `++`、`--`
的效果。
对于内置数值类型，它们不太可能有不寻常的行为，不过自定义类型也可以实现它们自己的 `succ` 以及 `pred` 方法，
所以在这种情况下，你可能需要注意 `++` 和 `--` 到底做了什么。

=== 指数

像你期望的那样工作，对比 Perl 5的 `{star}{star}` 运算符而言，Perl 6中它的优先级变的高于一元运算符（即 `-2{star}{star}4` 的值是
`-(2{star}{star}4)`，而不是 `(-2){star}{star}4`）。

=== 一元符号运算符

在 Perl 5中，一元运算符 `!` 和 `-` 分别是逻辑非和算术取反，可能需要注意的是它们会分别将参数强制为
`Bool` 以及 `Numeric`。
`~` 用做按位取反（将操作数视为1的补码），在文档中显示**有时**相当于 `!`
（这里原文有点混乱，~肯定不能直接相当于!）。

一元运算符 `~` 在 Perl 6中是字符串连接运算符，你可以使用 `+\^`来完成按位取反（`+^`也是一个二元运算符），
它会将操作数视为2的补码。

`+` 在 Perl 6中会对操作数有影响，它强制转换它的参数为数值类型。

一元运算符 `<\>` 已经不在了，如果你实在想引用一个已经存在的命名变量，你可以使用项上下文，就像这样
`$aref = item(@array)`，你可以通过使用 `&` 魔符得到一个命名子例程的引用：`$sref = &foo`。
匿名数组、哈希以及子例程在创建上__马上__返回它们的引用（奇怪，语句不是很通顺）。

=== 绑定运算符

`=~` 和 `!~` 分别被 `~~` 和 `!~~` 替代，那些在对 Perl 5中它们的表现有顾虑的人现在可以放心使用了，
在 Perl 6中它们更好用了，强类型意味着更少的猜测工作。

=== 乘法运算符

二元运算符 `*`、`/` 以及 `%` 在 Perl 5中分别为乘法、除法以及模除。

Perl 6中的二元运算符 `x` 稍微有点变化，作为对比，`print '-' x 80;` 将会返回给你一个80横线
的字符串（Perl 5&6 都如此），但是对于 Perl 5来说 `@ones = (1) x 80;` 返回给你一个80长度的由"1"组成的列表，在
Perl 6中你需要使用 `@ones = 1 xx 80;`。

=== 加法运算符

像你期望的那样，二元运算符 `+` 和 `-` 分别为加法和减法。

因 `.` 现在作为方法调用运算符，所以二元运算符 `~` 作为 Perl 6里面的连接运算符。

=== 移位运算符

`>>` 和 `<<` 已被 `+<` 和 `+>` 取代。

=== 一元命名运算符

像上面提到的那样，你将会在 https://docs.perl6.org/language/5to6-perlfunc[5to6-perlfunc]里找到它们。

=== 关系运算符

它们都和 Perl 5中的功能一样。

=== 比较运算符

`==` 和 `!=` 和 Perl 5中的语意一样。

`\<\=>` 和 `cmp` 在 Perl 6中有了不同的行为。
`\<\=>` 作为数值比较运算符，但是它不返回 Perl 5中的 `-1`、`0` 或者 `1`，而是
`<Order::Less`、`<Order::Same>` 或者 `<Order::More>`。
为了获取和 Perl 5中的 `cmp` 一样的行为（它也返回 `Order` 对象），你可以使用 `leg` 运算符

`cmp` 现在根据参数类型的不同行为如同 `\<\=>` 或者 `leg`。

`~~` 是 Perl 5中的智能匹配运算符，但是如同上面说到的，它__也是__ Perl 6中的匹配运算符。
对于 智能匹配运算符在 Perl 6中如何工作，请参考 https://design.perl6.org/S03.html#Smart_matching。

=== 智能匹配运算符

请参考上面的 `~~` 页面。

=== 按位与

二元运算符 `&` 在 Perl 6变成了 `+&`。

=== 按位或和异或

按位或从 Perl 5中的 `|` 变成了 Perl 6中的 `+|`，类似的，异或 `^` 现在是 `+^`。

=== C风格逻辑与

无变化。

=== C风格逻辑或

无变化。

=== 逻辑定义或

在 Perl 6中依然是 `//`，若第一个操作数已经定义则将其作为返回值，否则返回第二个操作数。
当然，它依然有一个低优先级的版本 `orelse`。

=== 区间运算符

在列表上下文，`..` 作为区间运算符这一点不需要做改变，另外还有几个开区间的版本可能会有很大的用处。
它们是：

.range
[cols="1,2,3,1,2",options="header",width="100%"]
|======================================
| 类型   | 运算符 | 描述 | 样例 | 结果
| infix  | ..^   | 不包含终点。        | 1..^5;   | 1 2 3 4
| infix  | ^..   | 不包含起点。        | 1^..5;   | 2 3 4 5
| infix  | \^..^ | 不包含起点以及终点。 | 1\^..^5; | 2 3 4
| prefix | ^    | 从0开始，不包含终点。 | ^5;      | 0 1 2 3 4
|======================================

在标量上下文，`..` 以及 `...` 在 Perl 5中作为翻转（flip-flop）运算符，但这很有有人知道，可能
更少被用到。
这些运算符在 Perl 6中使用 `ff` 以及 `fff` 取代了，但目前并没有清晰的文档化。

=== 条件运算符

`?:` 现在被替换成了 `??` `!!`，即你在 Perl 5中的代码 `$x = $ok ? $y : $z;` 在 Perl 6中
需要这样使用 `$x = $ok ?? $y !! $z;`。

=== 赋值运算符

虽然并没有完全文档化，不过 S03 表明数值以及逻辑赋值运算符都会如你期待的那样。
正如你所料由于 `.` 和 `~`的变化，一个值得注意的变化就是 `.=` 会调用左边对象的可修改方法，
同时 `~=` 用于字符串连接赋值。
还有，按位赋值运算符貌似不再区分数值以及字符串版本（`&=` 等 vs `&.=` 等），虽然这些特性在 Perl 5
中依然是实验性的，再一次，这些并没有明确的文档化。

=== 逗号运算符

逗号运算符如你期待的那样，但是技术上它用来创建 https://docs.perl6.org/type/List[列表] 或者分隔
函数调用参数，并且，函数调用也有使用 `:` 来将函数调用转换为方法调用的方式 - 参见 https://docs.perl6.org/language/operators#infix_%253A[这里]。

运算符 `\=>` 和 Perl 5中的“胖箭头”类似，它允许左侧的标志符不加引用，但是在 Perl 6中它用来构造 Pair 对象，
而不仅仅作为一个分隔符。
如果你尝试直接将 Perl 5的代码转换到 Perl 6，它的行为将不变。

=== 列表运算符

如同一元命名运算符一样，你可以在 https://docs.perl6.org/perl6.xhtml#_language_5to6-perlfunc.pod6[5to6-perlfunc.pod]
找到关于它的讨论。

=== 逻辑非

运算符 `!` 优先级较低的版本，正如 `!` 一样，强制将它的参数转换为 `Bool`。

=== 逻辑与

运算符 `&&` 的优先级较低的版本，行为与 Perl 5 中一致。

=== 逻辑或以及异或

`or` 是运算符 `||` 优先级较低的版本。
文档中列出了 `xor`，但没有描述它。

另外，还有运算符 `//` 优先级较低的版本, 叫做 `orelse`。

=== 引用以及引用类运算符

关于引用构造的细节，参见 https://docs.perl6.org/perl6.xhtml#_language_quoting.pod6[quoting]。

有些引用运算符允许原生字符串字面量：`Q` 或者 `｢…｣`,
尽管取决于你的键盘，这个字符可能很难找到。。。
反斜杠转义在 `Q` 引用字符串中不起作用，例如：`Q{This is still a closing curly brace → \}`
结果是 "This is This is still a closing curly brace → \"。

`q` 则如你所期待的那样，允许反斜杠转义，例如：`q{This is still a closing curly brace → \}, but this is → }`
将返回 "This is not a closing curly brace → }, but this is →",
在Perl 5 中，单引号与它行为一致。

`qq` 允许变量的内插，然而，默认情况下只有标量会被内插替换。想使用其它类型的变量作为插值，
你需要在它们之后加上方括号。例如： `@a = < 1 2 3 >; say qq/@a[] \example@example.com/;`
结果是 "1 2 3 \example@example.com"。哈希的内插可能有意料之外的方式：`%a = 1 \=> 2, 3 \=> 4;
say "%a[]";` 结果将会以空格分隔 Pair，制表符分隔每一个 Pair 的键和值（显然的）。
当然，你依然可以在字符串中使用花括号来内插你的 Perl 6 代码。
关于所有的细节，参见 https://docs.perl6.org/perl6.xhtml#_language_quoting.pod6-Interpolation%3A_qq[Interpolation]。

`qw` 跟 Perl 5 中一样，它还可以写成 `<...>` 这种形式，例如 `qw/a b c/` 等价与 `< a b c >`。

还有一个支持内插的 `qw` 版本（qw 本身不支持内插），它是 `qqw`，即 `my $a = 42; say qqw/$a b c/;`
将会返回 "42 b c"。

shell 引用现在通过使用 `qx`，不过你需要注意的是重音符（`）不在像 Perl 5 那样用于 shell 引用，
还有 Perl 变量在 `qx` 字符串中也不会作为插值。如果你想在 shell 命令行字符串中使用内插，你需要使用
`qqx` 作为替代品。

`qr` 运算符从 Perl 6 中移除了。

`tr///` 和 Perl 5 中的行为类似，唯一的警告就是指定区间的方式不同了，现在你应该使用 "a..z"，
而不是 "a-z"，即使用 Perl 6 的区间运算符。
`tr///` 有一个方法版本，并且被详细的文档化了，叫做 `.trans`，`.trans` 接受一个 Pair 的列表：
`$x.trans(['a'..'c'] \=> ['A'..'C'], ['d'..'q'] \=> ['D'..'Q'], ['r'..'z'] \=> ['R'..'Z']);`。
更多关于 `.trans` 的描述可以在 https://design.perl6.org/S05.html#Transliteration[Transliteration]
找到，等价物 `y///` 已经被废除。

在 Perl 6 中，heredoc有些不同，你要使用 `:to` 作为你的引用运算符，即 `q:to/END/;` 将会开始一段以
"END" 为结尾的 heredoc 。类似的，基于你选择的引用运算符，heredoc 可以支持转义或者内插，也就是说
字面量使用 `Q`，反斜杠转义使用 `q`，内插则使用 `qq`。

=== I/O运算符

关于 Perl 6 的输入/输出完整细节可以在 https://docs.perl6.org/perl6.xhtml#_language_io.pod6[io] 找到。

因为 `<...>` 作为 Perl 6 中的引用字符的构造一样，`<>` 不再用做按行读取文件，你可以在以文件名字创建的
`IO` 对象或者 `open` 打开的文件句柄上调用 `.lines` 来达到相同的目的。即 `my @a = "filename".IO.lines;`
或者 `my $h = open "filename", :r;my @a = $fh.lines;`（后者我们使用了 `:r` 来指定打开的文件用做读取）。
想要使用迭代的方式，你可以使用 `for` 循环：
[source, perl6]
--------------------------------
for 'huge-csv'.IO.lines -> $line {
    # Do something with $line
}
--------------------------------

注意这里的 `->`，这是 Block 语法的一部分。
在 Perl 6 中，`if`、`for`、`while` 等需要一个 Block。

如果你想读取文件内容到一个标量中，你可以 -- 幸福的事情！ -- 使用 `.slurp` 方法。
例子如下：
[source, perl6]
--------------------------------
my $x = "filename".IO.slurp;
# ... or ...
my $fh = open "filename", :r;
my $x = $fh.slurp;
--------------------------------

如同 https://docs.perl6.org/perl6.xhtml#_language_5to6-perlvar.pod6[5to6-perlvar.pod] 中提到
的一样，魔法输入文件句柄 `ARGV`  已经被 `$*ARGFILES` 取代了， 命令行参数数组 `@ARGV` 被
`@*ARGS` 取代。

=== 空操作

文档中虽然没有具体的指出，但是目前 `1 while foo();` 可以正常工作。

=== 按位字符串运算符

上面是分开介绍，这里是一个总结。

前缀运算符 `+^` 执行整数的按位取反，`?^` 执行布尔类型的按位取反。

`+&` 是按位与。

整数的按位或者是 `+|`，按位异或是中缀运算符 `+^`，布尔类型的按位或是 `?|`。

左移和右移现在是 `+<` 和 `+>`。
